name: Despliegue docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Checkout Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 Login docker GitHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Paso 3 - configurar la imagen docker
        run: docker build -t deployment .
      - name: Paso 4 - Ejecutar main
        run: |
          docker run deployment
