name: 0-Setup-Environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup:
    name: Configuración inicial
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Crear estructura de directorios
        run: |
          mkdir -p src/edu_pad/static/db
          mkdir -p src/edu_pad/static/csv
          mkdir -p src/edu_pad/static/logs
      
      - name: Actualizar setup.py si es necesario
        run: |
          if grep -q "sqlite3-simple" setup.py; then
            sed -i 's/"sqlite3-simple",\?//' setup.py
            echo "Se eliminó sqlite3-simple de setup.py"
          else
            echo "No se encontró sqlite3-simple en setup.py"
          fi
          
      - name: Instalar dependencias con setup.py
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Verificar instalación
        run: |
          python -c "import pandas; import requests; import openpyxl; from bs4 import BeautifulSoup; import sqlite3; print('Entorno configurado correctamente')"
          
      - name: Preparar estructura del proyecto
        run: |
          # Copiar los archivos Python al directorio src/edu_pad
          cp database.py dataweb.py main_extractor.py main_ingesta.py monitor.py src/edu_pad/ 2>/dev/null || true
          
          # Si no existen, crear archivos vacíos para evitar errores
          touch src/edu_pad/database.py
          touch src/edu_pad/dataweb.py
          touch src/edu_pad/main_extractor.py
          touch src/edu_pad/main_ingesta.py
          touch src/edu_pad/monitor.py
          
      - name: Guardar estructura del proyecto
        uses: actions/upload-artifact@v4
        with:
          name: project-structure
          path: |
            src/
            setup.py
          retention-days: 7