name: accionables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Paso 1 - Validar Repositorio
        uses: actions/checkout@v4

      - name: Paso 2 - Iniciar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: Paso 3 - Crear entorno virtual
        run: python -m venv venv
      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip
      - name: Paso 6 - Instalar dependencias
        run: pip install -e .
      - name: Paso 7 - Ejecutar Main
        run: python src/static/main.py
      - name: Paso 8 - Guardar el commit con el ultimo cambio desde pipeline
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Genera archivo csv de las web
          commit_user_name: Michelle Robinson [GitHub Actions]
          commit_user_email: michelle.robinson@est.iudigital.edu.co
          commit_author: Michelle Robinson <michelle.robinson@est.iudigital.edu.co>